name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: dpkg
      run: dpkg-scanpackages -m debs/ > Packages 

    - name: gzip
      run: gzip -c Packages > Packages.gz 

    - name: bzip2
      run: bzip2 -k Packages

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: repo
          path: ${{ github.workspace }}
